version: "3.2"
services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: docker_transcriber
    network_mode: "bridge"
    ports:
      - "5000-5900:5000-5900"
      - "5959:5959"
    environment:
      - HOSTNAME=localhost
      - RTCMIN_PORT=5000
      - RTCMAX_PORT=5900
      - WEBPAGE_PORT=5959
      - SERVER_IP=0.0.0.0
      # - ANNOUNCED_IP=192.168.1.101
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
    volumes:
      - type: bind
        source: ./keys
        target: /keys